### ISSUE TITLE
Indentation in the left pane for behaviors is offset incorrectly for second behavior

### ISSUE THREAD

**Issue by anselm** [joshmarinacci/mred-base-glitch#20]
<img width="247" alt="Screen Shot 2019-05-18 at 10 21 50 PM" src="https://user-images.githubusercontent.com/15317/57978131-978dab00-79bb-11e9-8cb3-8e8e49c44bf7.png">

**Comment by blairmacintyre** [comment]
I thought that at first, actually, but it's because of the flow of the items based on window width.  Open up that panel more (slide the divider with the 3D View to the right) and they will line up.
