### ISSUE TITLE
Login button disappears on click

### ISSUE THREAD

**Issue by anselm** [joshmarinacci/mred-base-glitch#21]
I posted a video on this in the slack https://files.slack.com/files-pri/T027LFU12-FJVTEE1QE/download/loginfail.mov

A quick workaround is to tab repeatedly until the system reaches that input box - and then input the string without using the mouse.

Another workaround if the bug is hard to find would be to turn on the "set active focus" for that input element.

**Comment by joshmarinacci** [comment]
fixed
